#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Memorize.Resource", IsApplication=true)]

namespace Memorize
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int sample_0 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sample_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sample_2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sample_3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sample_4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sample_5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sample_6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample_7 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample_back = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int texture = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050011
			public const int btnReset = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int firstColSection = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int fourthColSection = 2131034124;
			
			// aapt resource value: 0x7f050001
			public const int imageButton1 = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int imageButton10 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int imageButton11 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int imageButton12 = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int imageButton2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int imageButton3 = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int imageButton4 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int imageButton5 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int imageButton6 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int imageButton7 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int imageButton8 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int imageButton9 = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int secondColSection = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int thridColSection = 2131034120;
			
			// aapt resource value: 0x7f050010
			public const int txtWon = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
